image: "cuaesd/aesd-autotest"

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    # Specify to Docker where to create the certificates, Docker will
    # create them automatically on boot, and will create
    # `/certs/client` that will be shared between the service and job
    # container, thanks to volume mount from config.toml
    DOCKER_TLS_CERTDIR: "/certs"

test:
    stage: test
    script:
        - ./test.sh
